#!/usr/bin/env python3


configfile: "config/config.yaml"


include: "rules/common.smk"
include: "rules/busco_databases.smk"
include: "rules/ncbi_nucleotide_blast.smk"
include: "rules/ncbi_taxdump.smk"
include: "rules/uniprot_reference_proteomes.smk"


rule all:
    default_target: True
    input:
        to_storage("busco_databases"),
        to_storage("ncbi_nucleotide_blast"),
        to_storage("taxdump/TIMESTAMP"),
        to_storage("uniprot_referece_proteomes/reference_proteomes.tar.gz"),
