taxdump_url: ftp://ftp.ncbi.nih.gov/pub/taxonomy/new_taxdump/new_taxdump.tar.gz
blast_db_directory_url: ftp://ftp.ncbi.nlm.nih.gov/blast/db/v5
nt_filename_pattern: "nt.[0-9]{3}.tar.gz"
uniprot_directory_url: ftp://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/reference_proteomes
uniprot_filename_pattern: "Reference_Proteomes_2024_06.tar.gz"
output_bucket: "s3://pawsey1132.atol.refdata.v1"
