blast_db_directory_url: ftp://ftp.ncbi.nlm.nih.gov/blast/db/v5
busco_directory_url: https://busco-data.ezlab.org/v5/data
busco_manifest_path: file_versions.tsv
busco_domains:
  # options: Prokaryota, Eukaryota, Virus
  - Eukaryota
nr_database_path: "ftp://ftp.ncbi.nlm.nih.gov/blast/db/FASTA/nr.gz"
nt_filename_pattern: "nt.[0-9]{3}.tar.gz"
# Use snakemake prefixes, e.g. s3://endpoint.name for s3, or fs://path for
# local folders. The endpoint is currently configured in the profile.
buckets:
  busco: "s3://pawsey1132.atol.refdata.v0"
  default: "s3://pawsey1132.atol.refdata.v0"
  kraken: "s3://pawsey1132.atol.refdata.kraken"
  ncbi: "s3://pawsey1132.atol.refdata.v1"
  nr_diamond: "s3://pawsey1132.atol.refdata.nr.diamond"
  uniprot_diamond: "s3://pawsey1132.atol.refdata.uniprot.diamond"
  vecscreen: "s3://pawsey1132.atol.refdata.vecscreen"
# output_prefix: "fs://test/results"
taxdump_url: ftp://ftp.ncbi.nih.gov/pub/taxonomy/new_taxdump/new_taxdump.tar.gz
uniprot_directory_url: ftp://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/reference_proteomes
uniprot_filename_pattern: "Reference_Proteomes_\\d{4}_\\d{2}.tar.gz"
vecscreen_url: "https://raw.githubusercontent.com/sanger-tol/ascc/8903c1cc716f67e8bc46a17646dc7ffd633ee14c/assets/vecscreen_adaptors_for_screening_euks.fa"
# test datasets for reference assemblies
raw_reads_for_assembly:
  - assembly_id: "testassembly.tachina_grossa"
    initiative: dtol
    species_name: Tachina grossa
    taxid: 141258
    repo: ena
    input_data:
      - pacbio:
          - ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR108/037/ERR10879937/ERR10879937.fastq.gz
          - ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR108/038/ERR10879938/ERR10879938.fastq.gz
      - HiC:
          - r1: ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR108/047/ERR10890747/ERR10890747_1.fastq.gz
          - r2: ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR108/047/ERR10890747/ERR10890747_2.fastq.gz
  - assembly_id: "testassembly.valencia_hispanica"
    initiative: erga
    species_name: Valencia hispanica
    taxid: 195855
    repo: sra
    input_data:
      # these will need to be split with fasterq-dump
      - ont:
          - https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos2/sra-pub-run-34/ERR012/12119/ERR12119216/ERR12119216.1
      - illumina:
          - https://sra-pub-run-odp.s3.amazonaws.com/sra/ERR13767297/ERR13767297
          - https://sra-pub-run-odp.s3.amazonaws.com/sra/ERR13767298/ERR13767298
          - https://sra-pub-run-odp.s3.amazonaws.com/sra/ERR13767299/ERR13767299
          - https://sra-pub-run-odp.s3.amazonaws.com/sra/ERR13767300/ERR13767300
          - https://sra-pub-run-odp.s3.amazonaws.com/sra/ERR13767301/ERR13767301
          - https://sra-pub-run-odp.s3.amazonaws.com/sra/ERR13767302/ERR13767302
          - https://sra-pub-run-odp.s3.amazonaws.com/sra/ERR13767303/ERR13767303
          - https://sra-pub-run-odp.s3.amazonaws.com/sra/ERR13767304/ERR13767304
      - HiC:
          - https://sra-pub-run-odp.s3.amazonaws.com/sra/ERR13767294/ERR13767294
  - assembly_id: "testassembly.acritoscincus_duperreyi"
    initiative: ausarg
    species_name: Acritoscincus duperreyi
    taxid: 316450
    repo: sra
