blast_db_directory_url: ftp://ftp.ncbi.nlm.nih.gov/blast/db/v5
busco_directory_url: https://busco-data.ezlab.org/v5/data
busco_manifest_path: file_versions.tsv
nt_filename_pattern: "nt.[0-9]{3}.tar.gz"
# Use snakemake prefixes, e.g. s3://endpoint.name for s3, or fs://path for
# local folders. The endpoint is currently configured in the profile.
output_prefix: "s3://pawsey1132.atol.refdata.v0"
# output_prefix: "fs://test/results"
taxdump_url: ftp://ftp.ncbi.nih.gov/pub/taxonomy/new_taxdump/new_taxdump.tar.gz
uniprot_directory_url: ftp://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/reference_proteomes
uniprot_filename_pattern: "Reference_Proteomes_\\d{4}_\\d{2}.tar.gz"
